export const actionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",

    LOAD_CURRRENT_ITEM:"LOAD_CURRENT_ITEM",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    
    SET_CART_ITEMS:"SET_CART_ITEMS",
    ADD_TO_CART:"ADD_TO_CART", 
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    ADJUST_QTY:"ADJUST_QTY",
    UPDATE_PRODUCT_QUANTITY:"UPDATE_PRODUCT_QUANTITY",
    CLEAR_CART:"CLEAR_CART",

    INCREASE_CART_QUANTITY:"INCREASE_CART_QUANTITY",
    DECREASE_CART_QUANTITY:"DECREASE_CART_QUANTITY",

    SET_ADDRESS_LIST:"SET_ADDRESS_LIST",
    SELECTED_ADDRESS:"SELECTED_ADDRESS",
    DELETE_SELECTED_ADDRESS:"DELETE_SELECTED_ADDRESS",
    DELETE_ALL_ADDRESS:"DELETE_ALL_ADDRESS",

    DELETE_ADDRESS_FROM_LIST:"DELETE_ADDRESS_FROM_LIST",

    SET_USER_DETAILS:"SET_USER_DETAILS",
    SET_ORDERS_LIST:"SET_ORDERS_LIST"

}